
# docker-compose.yml
version: '3.1'
services:
  
  balaji-logging-service:
    build: ./
    container_name: "balaji-logging-service"
    hostname: "balaji-logging-service"
    ports:
      - "8080:8080"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: testlogging.log 